Implementing autocompletion support for PHPUnit annotation tags
Gert-dev/php-integrator-autocomplete-plus pull request #97
Opened 2017-04-12 12:12 UTC by msdm

2017-04-15 11:46 UTC, Gert-dev requested changes
Thanks for the submission. I added some minor feedback, but looks good overall!

2017-04-15 11:46 UTC, Gert-dev commented on lib/PHPUnitTagProvider.coffee
> +            documentationUrl = 'https://phpunit.de/manual/current/en/appendixes.annotations.html'
Could you complete the TODO and move this to the configuration class (you can take a gander at `DocblockTagProvider`, which also fetches it from the config).

2017-04-15 11:46 UTC, Gert-dev commented on lib/Main.coffee
> +        @providers.push(new PHPUnitTagProvider(@configuration))
Could you add a package setting that toggles this provider? I agree that adding PHPUnit annotations can be very handy for those that need them, but some users might be using PHPSpec or other testing tools and may not want to see these results.

2017-04-15 11:46 UTC, Gert-dev commented on lib/PHPUnitTagProvider.coffee
> +            {name: '@expectedException',              documentationName: 'expectedException',              snippet: '@expectedException ${1:exception}',            description: 'Sepcify the exception
Minor nitpick: did you mean `Specify` instead of `Sepcify` on this line and the following ones? 😄

2017-04-15 11:46 UTC, Gert-dev commented on lib/PHPUnitTagProvider.coffee
> +            {name: '@backupGlobals',                  documentationName: 'backupGlobals',                  snippet: '@backupGlobals ${1:disabled}',                 description: 'completely enable or
Minor nitpick: could you make the description start with an upper case letter (consistent with the other descriptions)?

2017-04-16 10:41 UTC, msdm commented
Thanks for the comments. Please see my new commit that addresses all these issues :)

2017-04-23 14:01 UTC, merged

2017-04-23 14:08 UTC, Gert-dev commented
Thanks for contributing this! I'll release 1.5.0 with these changes soon.